# Quick basics of NumPy

Numpy is traditionally imported with the name `np` to make it shorter to type repeatedly. It's also common to import often-used names individually at the same time.

In [4]:
import numpy as np
from numpy import pi, sin, cos


## Arrays

The core of NumPy is the `array`. This is a multi-dimensional array, which can be used to efficiently store numerical data (compared to the standard Python tools such as lists).

Most Python libraries for numerical work use NumPy as their back-end. Many functions in these libraries return NumPy arrays.

### Creating arrays

When a new array is needed, it can be created from various pre-existing objects (often Python lists). There are also many functions in NumPy that return arrays with different contents (such as arrays of random numbers).

For most functions that create arrays, the arrays _shape_ must be given as a tuple of integers, such as `(100, 2)` for an array of 100 rows and 2 columns, or `(20, 20, 20)` for a 20 cells wide data cube.

Note that a one-dimensional array with shape `(100,)` is different from a two-dimensional array with shape `(100,1)` or `(1,100)`. This distinction can be significant in some situations.

In [5]:
# A regular Python list:
numbers = [1.0, 15.0, -4.0, 12.0]

# A numpy array made from this list:
np.array(numbers)

array([  1.,  15.,  -4.,  12.])

In [23]:
# A list of Python lists:
numbers_2d = [[2,2], [3,4]]
np.array(numbers_2d)

array([[2, 2],
       [3, 4]])

In [7]:
# A numpy array made from a list:
np.array([np.sqrt(x) for x in range(10)])

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [12]:
# A numpy array with shape (50, 3), containing zeroes:
np.zeros((5, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [18]:
# For one-dimentional arrays an integer can be given as the shape:
np.zeros(3)

array([ 0.,  0.,  0.])

In [19]:
### The type of the array elements can be set manually. This is most often
# needed when an array of integers is required:
np.zeros((5, 4), dtype="i")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [24]:
# np.linspace(a, b, N) creates a 1-D array with N values evenly spaced from a to b:
np.linspace(0.0, 1.0, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [22]:
# np.arange() works exactly like Python's range() function, but returns an array
# instead of a Python list:
np.arange(10, dtype="f")

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.], dtype=float32)

### Array arithmetics

Normal arithmetic operations work on arrays element-wise. Operations with individual numbers also work as expected.

In [25]:
A = np.linspace(0, 1, 5)
B = np.linspace(10, 12, 5)

In [26]:
A+B

array([ 10.  ,  10.75,  11.5 ,  12.25,  13.  ])

In [27]:
A/2

array([ 0.   ,  0.125,  0.25 ,  0.375,  0.5  ])

In [28]:
B/A

/Users/owilkman/.virtualenvs/test/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([         inf,  42.        ,  22.        ,  15.33333333,  12.        ])

In [29]:
A*B

array([  0.   ,   2.625,   5.5  ,   8.625,  12.   ])

Comparison operators with numbers return arrays of truth values.

In [30]:
A < 0.6

array([ True,  True,  True, False, False], dtype=bool)

In [31]:
A == B

array([False, False, False, False, False], dtype=bool)

## Masked arrays

In [80]:
D = np.linspace(-5, 5, 11)
D

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [81]:
MD = np.ma.masked_array(D, mask=D<0)

In [82]:
D[1] = 100
D[5] = -200
MD

masked_array(data = [-- -- -- -- -- -200.0 1.0 2.0 3.0 4.0 5.0],
             mask = [ True  True  True  True  True False False False False False False],
       fill_value = 1e+20)

### Array indexing

Arrays are indexed with a similar syntax to Python lists. The different dimensions are separated with commas, but otherwise the syntax is practically the same.


In [36]:
C = np.random.uniform(0, 1, (10, 10))

In [37]:
C[:,0]

array([ 0.13701147,  0.568855  ,  0.94937067,  0.25324507,  0.82227909,
        0.77411587,  0.28388461,  0.60487617,  0.41011629,  0.02081486])

In [38]:
C[:, 1:4]

array([[ 0.34250021,  0.14357108,  0.50189439],
       [ 0.25994229,  0.04512536,  0.12013059],
       [ 0.86258728,  0.05840016,  0.67781497],
       [ 0.31084921,  0.05093668,  0.22738337],
       [ 0.2355004 ,  0.77326334,  0.55785909],
       [ 0.24951063,  0.74487009,  0.44004284],
       [ 0.09932246,  0.96868711,  0.54490048],
       [ 0.98185925,  0.4399237 ,  0.86486838],
       [ 0.70019615,  0.41973647,  0.56472182],
       [ 0.65419911,  0.38856358,  0.0829369 ]])

Arrays can also be index with a truth value array, which acts as a filter:

In [39]:
X = np.linspace(0.0, 5.0, 11)
X

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [40]:
X[X<3]

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5])

### Array attributes and methods

Like everything in Python, arrays are objects, and have several useful methods and attributes. 

The _attributes_ are not functions (methods), but fields of the object containing metadata about its shape, size, data type, memory layout etc.. There are a few more used ones:

- `A.shape` is a tuple containing the shape of the array
- `A.size` is the total number of elements in the array
- `A.ndims` is the number of dimensions

If `A.shape == (10,2,2)`, then `A.size == 40` and `A.ndims == 3`.

The _methods_ are functions associated with the object, which perform some computation or alteration on the array. Some common ones include:

- `A.sum()` computes the sum of all the elements in the array.
- `A.cumsum()` computes the cumulative sum of all the elements in the array.
- `A.mean()` computes the mean value of the elements.
- `A.std()` computes the standard deviation of the elements.
- `A.min()` and `A.max()` give the minimum and maximum values in the array.
- `A.argmin()` and `A.argmax()` give the indices of the minimum and maximum values.
- `A.sort(n)` sorts the array along the `n`th axis. The default is `-1`, the last axis.

Some of the methods have function equivalents in NumPy. For example, if `A` is an array, then `A.cumsum()` is equivalent to `np.cumsum(A)`.

The attribute-like `A.T` returns a transposed copy of the array. This mostly makes sense for 2-D arrays, but the difference between a row vector and a column vector can sometimes matter. Arrays with dimension larger than two can also be transposed.

See here for the full list of attributes and methods: http://docs.scipy.org/doc/numpy-1.10.0/reference/arrays.ndarray.html

In [41]:
A = np.array([1.0, -2.0, 3.0, 5.0, 2.0])

print(A.min(), A.max())
print(A.argmin(), A.argmax())

-2.0 5.0
1 3


## Mathematical functions

NumPy contains a wide variety of mathematical functions, as one might expect. All of the functions which operate on individual numbers are applied element-wise on arrays.

Some common functions include:

- Trigonometric: `sin`, `cos`, `tan`, `arcsin`, `arccos`, `arctan`, `arctan2`
- Hyperbolic: `sinh`, `cosh`, `tanh` and their arc-versions
- Exponential: `exp`, `log`, `log10`, `log2` (`log` is the natural logarithm)
- Conversions: `degrees` and `radians`
- Rounding: `round`, `ceil`, `floor`
- Array reductions: `sum`, `prod`, `cumsum`, `cumprod`
- Miscellaneous: `sqrt`, `sign`

The full list of mathematical functions can be found here: http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.math.html

In [47]:
X = np.linspace(0.0, 2.0, 5)

print("X =", X)
print("exp(X) =", np.exp(X))
print("sqrt(X) = ", np.sqrt(X))
print("cumsum(X) =", np.cumsum(X))

X = [ 0.   0.5  1.   1.5  2. ]
exp(X) = [ 1.          1.64872127  2.71828183  4.48168907  7.3890561 ]
sqrt(X) =  [ 0.          0.70710678  1.          1.22474487  1.41421356]
cumsum(X) = [ 0.   0.5  1.5  3.   5. ]


## Random generators

The submodule `numpy.random` contains a wide variety of random number generators. Two common ones are:

- Standard uniform $U(0,1)$: `rand`
- Standard normal $N(0,1)$: `randn`

For some reason (Matlab compatibility?), the shape of the output array is given differently for these two functions: instead of a tuple, the shape is given as individual integer parameters. This can confuse sometimes!

Below we create arrays with shape `(2,2)`, from the normal distribution $N(0,1)$ and the gamma distribution $\text{Gamma}(0, 1)$.


In [50]:
# Shape as two separate integers:
np.random.randn(2,2)

array([[-1.03077509,  1.63345059],
       [ 0.63494436, -1.5790757 ]])

In [52]:
# However, for others, the shape is a tuple like usual:
np.random.gamma(1, 2, (2,2))

array([[ 0.41933058,  1.78708324],
       [ 0.12619899,  0.22086469]])

In [51]:
np.random.normal(0.0, 1.0, (2,2)) # equivalent to M1

array([[ 0.21425167, -1.17950703],
       [-0.01592099, -0.45682954]])

## Linear algebra

## Arrays in linear algebra

One-dimensional arrays can be used as vectors and two-dimensional arrays as matrices. However, as you saw above, the multiplication of arrays is element-wise multiplication, not matrix multiplication. Matrix multiplication of arrays can be performed with the function `np.matmul`. This returns an array.

An array filled like an identity matrix can be created with `np.eye(N)`, where `N` is the width of the array.

In [83]:
# Define an identity array and two 2x2 arrays
I = np.eye(2)
X = np.array([[1,2],[3,4]])

In [87]:
# Element-wise multiplication
I*X

array([[ 1.,  0.],
       [ 0.,  4.]])

In [88]:
# Matrix multplication
np.dot(I,X)

array([[ 1.,  2.],
       [ 3.,  4.]])

## Matrix objects

NumPy also has a separate type for matrices. This is a completely separate array type and works slightly differently from regular arrays. Most improtantly, multiplication between matrices follow matrix multiplication.

A matrix can be made from an array with the function `np.matrix`.

In [98]:
# Matrix multiplication
Id = np.matrix(I)
M = np.matrix(X)
Id * M

matrix([[ 1.,  2.],
        [ 3.,  4.]])

The linear algebra functions are found in the submodule `np.linalg`. Some important ones are:

- `np.linalg.dot` computes the dot product of two vectors (1-D arrays or matrices)
- `np.linalg.cross` computes the cross product of two vectors
- `np.linalg.norm` computes the L2 norm of a vector or matrix
- `np.linalg.inv` computes the inverse of a matrix

There are also various functions for solving linear equations, computing eigenvalues and factorizations etc.

Documentation for `numpy.linalg`: http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html

In [96]:
# Example, inverse matrix
np.linalg.inv(I*M)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

## SciPy

SciPy is a Python package containing many tools for scientific computations. It uses NumPy arrays and these days it is included with a NumPy installation.

SciPy contains tools for "optimization, linear algebra, integration, interpolation, special functions, FFT, signal and image processing, ODE solvers and other tasks common in science and engineering". There is some overlap between NumPy and SciPy. For example `scipy.linalg` contains all of the same linear algebra functions as `numpy.linalg`, plus some more advanced ones.

### Curve fitting with SciPy

There is a very wide variety of different tools in SciPy. For this tutorial we'll only look at one fairly common optimization problem.

`scipy.optimize.curve_fit` is a function which can be used to fit an arbitrary model of the form $y = f(x; a, b, \ldots) + \epsilon$, where the unknown parameters to be estimated are $a, b, \ldots$, and $\epsilon$ is random noise.


In [99]:
from scipy.optimize import curve_fit

Calling `curve_fit` requires us to define a model. This is a function that takes the `x` array and the parameters. For example, let's define the model

\begin{equation}
    y = a \sin(b x)
\end{equation}

and also generate some data with this model.

In [100]:
def model(X, a, b):
    return a * np.sin(b*X)

X = np.linspace(0, 5, 10)
epsilon = 0.1 * np.random.randn(10) # random noise
Y = model(X, 2.0, 0.33) + epsilon

Now, we had some data vectors `X` and `Y`, and we can fit the model paramters to that data by calling

In [104]:
params, cov = curve_fit(model, X, Y)

The function returns two arrays: the first one contains the best-fit parameter values, and the second one is the covariance matrix of the parameters.

In [105]:
print("Best-fit a = {:.5}, b = {:.5}".format(params[0], params[1]))

Best-fit a = 1.9603, b = 0.35529
